name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.2.3
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.1
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12
  emoji_picker_flutter: ^1.6.1
  http: ^1.1.0
  html: ^0.15.4
  any_link_preview: ^3.0.1
  progress_indicators: ^1.0.0
  image_picker: ^0.8.7+4
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
