name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.2.4
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^6.0.0
  intl: ^0.19.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^3.1.0
  http: ^1.2.2
  html: ^0.15.4
  any_link_preview: ^3.0.2
  progress_indicators: ^1.0.0
  image_picker: ^1.1.2
  audio_waveforms: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
