name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.2.3
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl: ^0.18.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.11
  emoji_picker_flutter: ^1.5.4
  http: ^0.13.5
  html: ^0.15.3
  any_link_preview: ^3.0.0
  progress_indicators: ^1.0.0
  image_picker: ^0.8.7+5
  audio_waveforms: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
